### ISSUE TITLE
Simulation of actual rocket flying is incomplete

### ISSUE THREAD

**Issue by k9ur** [otta8634/Hackathon-ComSSA-2022#2]
Need to code both the functions to simulate it, and also functions to graph its trajectory.
Is required both for the presentation, and for calculating optimal angles to launch at & when, etc. (data required by @jsun1590).

**Comment by jsun1590** [comment]
lazy fk still haven't completed the issue from almost a year ago.

**Comment by k9ur** [comment]
Competition has ended, and this wouldn't be possible with how the Python simulation was made anyway.
